CREATE TABLE drop_categories (
id INTEGER PRIMARY KEY NOT NULL,
name TEXT NOT NULL,
icon TEXT NOT NULL,
drop_type TEXT NOT NULL,
budget INTEGER NOT NULL DEFAULT 0,
sort INTEGER NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE bucket_categories (
id INTEGER PRIMARY KEY NOT NULL,
name TEXT NOT NULL,
icon TEXT NOT NULL,
balance_type TEXT NOT NULL,
sort INTEGER NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE buckets (
id INTEGER PRIMARY KEY NOT NULL,
name TEXT NOT NULL,
is_income_default BOOLEAN NOT NULL DEFAULT false,
is_expense_default BOOLEAN NOT NULL DEFAULT false,
bucket_category_id INTEGER NOT NULL,
sort INTEGER NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(bucket_category_id) REFERENCES bucket_categories(id) ON DELETE RESTRICT ON UPDATE NO ACTION);

CREATE TABLE bucket_snaps (
id INTEGER PRIMARY KEY NOT NULL,
bucket_id INTEGER NOT NULL,
amount INTEGER NOT NULL,
snapped_on DATE NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(bucket_id) REFERENCES buckets(id) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE subscribed_drops (
id INTEGER PRIMARY KEY NOT NULL,
from_bucket_id INTEGER,
to_bucket_id INTEGER,
drop_category_id INTEGER,
title TEXT NOT NULL,
amount INTEGER NOT NULL,
frequency TEXT NOT NULL,
repeat_interval INTEGER NOT NULL DEFAULT 1,
starts_on DATE NOT NULL,
ends_on DATE,
is_active BOOLEAN NOT NULL DEFAULT true,
notes TEXT,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(from_bucket_id) REFERENCES buckets(id) ON DELETE RESTRICT ON UPDATE NO ACTION,
FOREIGN KEY(to_bucket_id) REFERENCES buckets(id) ON DELETE RESTRICT ON UPDATE NO ACTION,
FOREIGN KEY(drop_category_id) REFERENCES drop_categories(id) ON DELETE SET NULL ON UPDATE NO ACTION);

CREATE TABLE drops (
id INTEGER PRIMARY KEY NOT NULL,
from_bucket_id INTEGER,
to_bucket_id INTEGER,
drop_category_id INTEGER,
subscribed_drop_id INTEGER,
parent_drop_id INTEGER,
title TEXT NOT NULL,
amount INTEGER NOT NULL,
dropped_on DATE NOT NULL,
notes TEXT,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(from_bucket_id) REFERENCES buckets(id) ON DELETE RESTRICT ON UPDATE NO ACTION,
FOREIGN KEY(to_bucket_id) REFERENCES buckets(id) ON DELETE RESTRICT ON UPDATE NO ACTION,
FOREIGN KEY(drop_category_id) REFERENCES drop_categories(id) ON DELETE SET NULL ON UPDATE NO ACTION,
FOREIGN KEY(subscribed_drop_id) REFERENCES subscribed_drops(id) ON DELETE SET NULL ON UPDATE NO ACTION,
FOREIGN KEY(parent_drop_id) REFERENCES drops(id) ON DELETE CASCADE ON UPDATE NO ACTION);

